# Generated by Django 5.1.7 on 2025-03-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('file', models.FileField(blank=True, null=True, upload_to='users/{user.username}', verbose_name='Файл')),
                ('comment', models.TextField(null=True)),
                ('size', models.CharField(null=True)),
                ('link_download', models.CharField(blank=True, null=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('lastload', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=250)),
            ],
        ),
    ]
