# Generated by Django 5.1.7 on 2025-04-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='user_files/%Y/%m/%d/')),
                ('name', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('size', models.BigIntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('last_download', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('link_download', models.CharField(blank=True, max_length=50, unique=True)),
            ],
        ),
    ]
