# Generated by Django 5.1.7 on 2025-03-31 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='user',
            new_name='owner_files',
        ),
    ]
