# Generated by Django 5.1.7 on 2025-03-31 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_rename_user_file_owner_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='owner_files',
            new_name='owner',
        ),
    ]
