# Generated by Django 5.1.7 on 2025-09-09 19:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_file_is_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-published'], 'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterField(
            model_name='file',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(max_length=50, verbose_name='Тип файла'),
        ),
        migrations.AlterField(
            model_name='file',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Публичный доступ'),
        ),
        migrations.AlterField(
            model_name='file',
            name='last_download',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего скачивания'),
        ),
        migrations.AlterField(
            model_name='file',
            name='link_download',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Специальная ссылка'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='file',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(verbose_name='Размер в байтах'),
        ),
    ]
