# Generated by Django 5.1.7 on 2025-09-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='storage_path',
            field=models.CharField(blank=True, help_text='Относительный путь к папке пользователя в файловом хранилище', max_length=255, verbose_name='Путь к хранилищу'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Определяет, является ли пользователь администратором системы', verbose_name='Администратор'),
        ),
    ]
