# Generated by Django 5.1.7 on 2025-09-09 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_user_storage_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 9, 9, 14, 10, 52, 866291, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
